### PR TITLE
3.0/feature/module/slider

### PR DESCRIPTION
**Pull request by alexanderbomanskoug2**

### CODE REVIEW

**Review by nRamstedt — CHANGES_REQUESTED** [review]
- Container showing even when slide module has no content
- Set primary background on container as default
- Fix naming convention on modifiers

**Comment by alexanderbomanskoug2** [comment]
https://github.com/helsingborg-stad/styleguide/pull/307
https://github.com/helsingborg-stad/blade-component-library/pull/143
https://github.com/helsingborg-stad/Modularity/pull/107

**Comment by nRamstedt** [comment]
Indicitators still small & not clickable

**Review by nRamstedt — CHANGES_REQUESTED** [review]
FIx indicators

**Review by nRamstedt — CHANGES_REQUESTED** [review]
- Make indicators larger & more visible
- Make sure indicators get extra spacing in bottom
- Make container padding 24px @ mobile

**Review by nRamstedt — APPROVED** [review]

**Review by nRamstedt — APPROVED** [review]

**Pull request merged**
